server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rwtool_ops
    username: postgres
    password: your_password_here
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update        # creates/updates tables automatically
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # optional — you can delete this if you don't use H2
  h2:
    console:
      enabled: false

  # FTP configuration (for your Ops module)
  ftp:
    host: ftp.example.com
    port: 21
    user: ftpuser
    password: ftppassword
    remote-dir: /incoming
    local-dir: ./rw-storage

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
